// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";

const SUPABASE_URL = "https://iuqnowcnpxsyqeznnqfp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY =
  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml1cW5vd2NucHhzeXFlem5ucWZwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAyMzE5MDUsImV4cCI6MjA2NTgwNzkwNX0.iOHiOWz2PnL4tsxs90RLW7zeFmRCftVPprM9SpqFBnA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(
  SUPABASE_URL,
  SUPABASE_PUBLISHABLE_KEY,
);
