// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ufjzxhohsvuxxyajvzma.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVmanp4aG9oc3Z1eHh5YWp2em1hIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAxODMyNzAsImV4cCI6MjA2NTc1OTI3MH0.ViCHjvXnmZMux7itgs9_jG1VEun0nbl1ESjKPl9om-w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);